apiVersion: v1
kind: Service
metadata:
  name: zero-touch-api-service
  namespace: zero-touch-it-ops
spec:
  type: ClusterIP
  selector:
    app: zero-touch-api
  ports:
    - port: 80
      targetPort: 8001