apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-touch-api
  namespace: zero-touch-it-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zero-touch-api
  template:
    metadata:
      labels:
        app: zero-touch-api
    spec:
      containers:
        - name: zero-touch-api
          image: chefallacr.azurecr.io/zero-touch-it-ops:1.0
          ports:
            - containerPort: 8001